image: docker:latest

services:
  - docker:dind
stages:
  - build_and_deploy
job:
  stage: build_and_deploy
  script:
    - mkdir ~/.docker
    - echo '{"experimental":"enabled"}' | tee ~/.docker/config.json
    - apk add --no-cache openjdk8 maven ca-certificates
    - export JAVA_HOME=/usr/lib/jvm/default-jvm
    - export PATH="$JAVA_HOME/bin:${PATH}"
    - echo "${CONTAINER_REGISTRY_PASSWORD}" | docker login -u "${CONTAINER_REGISTRY_USERNAME}" --password-stdin
    - mvn clean install
